create table roles (id int8 generated by default as identity, role_name varchar(255), primary key (id));
create table users (id int8 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table users_roles (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles;
alter table if exists users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users;
